# Generated by Django 4.0.4 on 2023-07-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
